name: Gen char ids

on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  gen-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
          
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: scripts/node/gen-char-id

      - name: Run script
        run: node scripts/node/gen-char-id/index.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add generated_data/characterid.json
          
          git diff --staged --quiet || git commit -m "chore(gen): character ids"
          git push origin main
        shell: bash
